version: '3.3'
services:
  plex:
    image: siwakorn2345/plex:sw06
    networks:
     - webproxy
    logging:
      driver: json-file
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.plex888-https.entrypoints=websecure
        - traefik.http.routers.plex888-https.rule=Host("plex888.xops.ipv9.me")
        - traefik.http.routers.plex888-https.tls.certresolver=default
        - traefik.http.services.plex888.loadbalancer.server.port=32400
      resources:
        reservations:
          cpus: '0.1'
          memory: 6M
        limits:
          cpus: '0.4'
          memory: 250M
networks:
  webproxy:
    external: true
