version: '3.3'
services:
  test-volume:
    image: siwakorn2345/swarm01-backend:01
    networks:
     - webproxy
    logging:
      driver: json-file
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.http.routers.whale0011-https.entrypoints=websecure
        - traefik.http.routers.whale0011-https.rule=Host("whale0011.xops.ipv9.me")
        - traefik.http.routers.whale0011-https.tls.certresolver=default
        - traefik.http.services.whale0011.loadbalancer.server.port=80
      resources:
        reservations:
          cpus: '0.1'
          memory: 6M
        limits:
          cpus: '0.4'
          memory: 50M
networks:
  webproxy:
    external: true
